# Generated by Django 5.2.5 on 2025-09-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('refRay', models.AutoField(primary_key=True, serialize=False)),
                ('nomRay', models.CharField(max_length=100)),
            ],
        ),
    ]
