# Generated by Django 5.2.5 on 2025-09-08 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_contenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_fabr',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
