# Generated by Django 5.2.5 on 2025-09-11 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_produit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date_fabr',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
